-- Run this once in Supabase SQL editor if public.property_images does not exist yet.
create table if not exists public.property_images (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete cascade,
  image_url text not null,
  storage_path text not null,
  display_order integer not null default 0,
  is_cover boolean not null default false,
  alt_text text,
  created_at timestamptz not null default now()
);

create index if not exists property_images_property_id_display_order_idx
  on public.property_images(property_id, display_order);

create unique index if not exists property_images_one_cover_per_property_idx
  on public.property_images(property_id)
  where is_cover;
