-- 주 1회 매물 확인 자동전화용 테이블
create table if not exists public.property_call_contacts (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete cascade,
  contact_name text,
  phone text not null,
  enabled boolean not null default true,
  last_called_at timestamptz,
  last_checked_at timestamptz,
  next_check_at timestamptz default now(),
  last_result text,
  last_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(property_id, phone)
);

create table if not exists public.property_call_logs (
  id bigint generated by default as identity primary key,
  contact_id bigint not null references public.property_call_contacts(id) on delete cascade,
  property_id bigint not null references public.properties(id) on delete cascade,
  provider_call_id text,
  result text,
  note text,
  called_at timestamptz not null default now(),
  answered_at timestamptz
);

create index if not exists property_call_contacts_due_idx
  on public.property_call_contacts(enabled, next_check_at);
create index if not exists property_call_logs_contact_idx
  on public.property_call_logs(contact_id, called_at desc);

alter table public.property_call_contacts enable row level security;
alter table public.property_call_logs enable row level security;
-- 관리자 API는 service role 키를 사용하므로 별도 공개 RLS 정책은 만들지 않습니다.
