create table if not exists public.site_page_views (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  path text not null,
  visitor_id text not null,
  session_id text not null,
  referrer text,
  source text,
  device text,
  utm_source text,
  utm_medium text,
  utm_campaign text
);

create index if not exists site_page_views_created_at_idx
  on public.site_page_views (created_at desc);

create index if not exists site_page_views_path_idx
  on public.site_page_views (path);

create index if not exists site_page_views_visitor_id_idx
  on public.site_page_views (visitor_id);

alter table public.site_page_views enable row level security;

-- 방문기록은 Next.js 서버 API가 service role로만 읽고/쓰기 합니다.
-- anon/authenticated 사용자의 직접 접근은 허용하지 않습니다.
revoke all on table public.site_page_views from anon, authenticated;
