"use client";
import { useEffect,useMemo,useState } from "react";
type Session={sessionId:string;visitorId:string;startedAt:string;source:string;landingPath:string;landingTitle?:string;pageViews:number;uniquePages:number;device:string;pages:Array<{path:string;title?:string}>;suspectedBot?:boolean};
type AnalyticsData={ok:boolean;setupNeeded?:boolean;error?:string;summary?:{todayViews:number;todayVisitors:number;todaySessions:number;yesterdayViews:number;yesterdayVisitors:number;last30Views:number;last30Visitors:number;last30Sessions:number;suspectedBotSessions?:number;suspectedBotViews?:number};daily?:Array<{date:string;views:number;visitors:number;sessions:number}>;topPages?:Array<{path:string;views:number;visitors:number;title?:string}>;sources?:Array<{source:string;views:number;visitors:number}>;devices?:Array<{device:string;views:number;visitors?:number}>;recentSessions?:Session[];suspectedSessions?:Session[]};
const deviceLabel:Record<string,string>={mobile:"모바일",desktop:"PC",tablet:"태블릿",unknown:"기타"};
function StatCard({label,value,note}:{label:string;value:number;note?:string}){return <div className="rounded-3xl bg-white p-6 shadow-sm"><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-[#0A2342]">{value.toLocaleString()}</p>{note?<p className="mt-2 text-xs text-slate-400">{note}</p>:null}</div>}
function pageLabel(i:{path:string;title?:string}){if(i.title)return i.title;if(i.path==="/")return"홈페이지 메인";if(i.path==="/search")return"매물 검색";return i.path}
function sourceLabel(s:string){if(s==="네이버"||s==="naver")return"네이버";if(s==="구글"||s==="google")return"구글";if(s==="직접 유입"||s==="direct")return"직접 유입";return s||"기타"}
function SessionRows({items,bot=false}:{items:Session[];bot?:boolean}){return <div className="divide-y divide-slate-100">{items.length===0?<p className="py-8 text-center text-sm text-slate-500">데이터가 없습니다.</p>:items.map(s=><div key={s.sessionId} className="py-5"><div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><div className="min-w-0"><p className="font-semibold">{new Intl.DateTimeFormat("ko-KR",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(s.startedAt))} · {sourceLabel(s.source)} · {deviceLabel[s.device]??s.device}{bot?" · 자동 접근 의심":""}</p><p className="mt-1 truncate text-sm text-slate-500">첫 페이지: {pageLabel({path:s.landingPath,title:s.landingTitle})}</p></div><div className="text-sm text-slate-500">조회 {s.pageViews}회 · 페이지 {s.uniquePages}개</div></div>{s.pages.length>1?<p className="mt-2 line-clamp-2 text-xs text-slate-400">이동: {s.pages.map(pageLabel).join(" → ")}</p>:null}</div>)}</div>}
export default function AdminAnalyticsPage(){const[data,setData]=useState<AnalyticsData|null>(null),[loading,setLoading]=useState(true);useEffect(()=>{localStorage.setItem("baekjo_analytics_exclude","1");void fetch("/api/analytics",{cache:"no-store"}).then(async r=>setData(await r.json())).catch(()=>setData({ok:false,error:"방문 통계를 불러오지 못했습니다."})).finally(()=>setLoading(false))},[]);const maxDaily=useMemo(()=>Math.max(1,...(data?.daily??[]).map(i=>i.views)),[data?.daily]);if(loading)return <main className="min-h-screen bg-slate-100 p-8"><div className="mx-auto max-w-7xl rounded-3xl bg-white p-12 text-center">방문 통계를 불러오는 중입니다.</div></main>;if(!data?.ok)return <main className="min-h-screen bg-slate-100 p-8"><div className="mx-auto max-w-4xl rounded-3xl bg-white p-8">{data?.error||"방문 통계를 불러오지 못했습니다."}</div></main>;const s=data.summary!;return <main className="min-h-screen bg-slate-100 px-4 py-8 text-[#0A2342] sm:px-6"><div className="mx-auto max-w-7xl"><section className="rounded-[30px] bg-[#0A2342] p-7 text-white"><div className="flex justify-between gap-5"><div><p className="text-sm font-semibold tracking-[.24em] text-[#C9A227]">VISITOR ANALYTICS</p><h1 className="mt-3 text-3xl font-bold">홈페이지 방문 분석</h1><p className="mt-3 text-sm text-white/70">실제 방문 통계와 자동 접근 의심 트래픽을 분리해 표시합니다.</p></div><button onClick={()=>location.reload()} className="rounded-full border border-white/20 px-5 py-3 text-sm font-semibold">새로고침</button></div></section>
<section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><StatCard label="오늘 방문자" value={s.todayVisitors} note={s.yesterdayVisitors?`어제 대비 ${Math.round(((s.todayVisitors-s.yesterdayVisitors)/s.yesterdayVisitors)*100)}%`:"어제 비교 데이터 없음"}/><StatCard label="오늘 페이지뷰" value={s.todayViews} note={`세션 ${s.todaySessions}회`}/><StatCard label="어제 방문자" value={s.yesterdayVisitors} note={`페이지뷰 ${s.yesterdayViews}회`}/><StatCard label="최근 30일 방문자" value={s.last30Visitors} note={`세션 ${s.last30Sessions}회`}/><StatCard label="최근 30일 페이지뷰" value={s.last30Views}/><div className="rounded-3xl border border-amber-200 bg-amber-50 p-6 shadow-sm"><p className="text-sm font-medium text-amber-700">자동 접근 의심</p><p className="mt-2 text-3xl font-bold text-amber-900">{(s.suspectedBotSessions??0).toLocaleString()}</p><p className="mt-2 text-xs text-amber-600">조회 {(s.suspectedBotViews??0).toLocaleString()}회 · 실제 방문 통계에서 제외</p></div></section>
<section className="mt-6 rounded-[28px] bg-white p-6"><h2 className="text-xl font-bold">최근 14일 방문 추이</h2><p className="mt-1 text-sm text-slate-500">자동 접근 의심을 제외한 방문입니다.</p><div className="mt-6 grid grid-cols-7 gap-2 md:grid-cols-14">{(data.daily??[]).map(i=><div key={i.date} className="flex min-w-0 flex-col items-center gap-2"><span className="text-xs font-semibold">{i.visitors}</span><div className="flex h-40 w-full items-end rounded-2xl bg-slate-100 p-1"><div className="w-full rounded-xl bg-[#C9A227]" style={{height:`${Math.max(4,(i.views/maxDaily)*100)}%`}}/></div><span className="text-[11px] text-slate-400">{i.date.slice(5)}</span></div>)}</div></section>
<div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-[28px] bg-white p-6"><h2 className="text-xl font-bold">유입경로 TOP 10</h2><div className="mt-5 divide-y">{(data.sources??[]).map(i=><div key={i.source} className="flex justify-between py-4"><b>{sourceLabel(i.source)}</b><span className="text-sm text-slate-500">방문자 {i.visitors} · 조회 {i.views}</span></div>)}</div></section><section className="rounded-[28px] bg-white p-6"><h2 className="text-xl font-bold">인기 페이지 TOP 10</h2><div className="mt-5 divide-y">{(data.topPages??[]).map(i=><div key={i.path} className="flex justify-between gap-4 py-4"><div className="min-w-0"><b className="block truncate">{pageLabel(i)}</b>{i.title?<span className="text-xs text-slate-400">{i.path}</span>:null}</div><span className="shrink-0 text-sm text-slate-500">방문자 {i.visitors} · 조회 {i.views}</span></div>)}</div></section></div>
<section className="mt-6 rounded-[28px] bg-white p-6"><h2 className="text-xl font-bold">최근 실제 방문 흐름</h2><p className="mt-1 text-sm text-slate-500">자동 접근 의심 세션을 제외했습니다.</p><SessionRows items={data.recentSessions??[]}/></section>
<section className="mt-6 rounded-[28px] border border-amber-200 bg-amber-50 p-6"><h2 className="text-xl font-bold text-amber-900">자동 접근 의심</h2><p className="mt-1 text-sm text-amber-700">직접 유입 · PC · SEO 랜딩페이지 1개만 조회하고 종료한 반복 패턴입니다. 삭제하지 않고 별도 보관합니다.</p><SessionRows items={data.suspectedSessions??[]} bot/></section>
<section className="mt-6 rounded-[28px] bg-white p-6"><h2 className="text-xl font-bold">접속 기기</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(data.devices??[]).map(i=><div key={i.device} className="rounded-2xl bg-slate-50 p-5"><p className="text-sm text-slate-500">{deviceLabel[i.device]??i.device}</p><p className="mt-2 text-2xl font-bold">방문자 {(i.visitors??0).toLocaleString()}</p><p className="mt-1 text-sm text-slate-400">조회 {i.views.toLocaleString()}회</p></div>)}</div></section></div></main>}
