"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { supabase } from "@/lib/supabase";
import { normalizePropertyForDisplay } from "@/lib/property-normalize";
import { formatPropertyPriceDisplay } from "@/lib/property-price";
import { Property } from "@/types/property";

export default function FeaturedProperties() {
  const [properties, setProperties] = useState<Property[]>([]);
  const [loading, setLoading] = useState(true);
  const [errorMessage, setErrorMessage] = useState("");
  useEffect(() => { async function getProperties() { const { data, error } = await supabase.from("properties").select("*, property_images(*)").order("created_at", { ascending: false }).limit(24); if (error) { setErrorMessage("매물을 불러오지 못했습니다."); setLoading(false); return; } const visibleProperties = ((data || []) as Property[]).filter((p) => p.is_hidden !== true).map(normalizePropertyForDisplay).sort((a,b)=>{ const f=Number(b.is_featured)-Number(a.is_featured); if(f!==0)return f; const o=(a.display_order??0)-(b.display_order??0); if(o!==0)return o; return (b.created_at?new Date(b.created_at).getTime():0)-(a.created_at?new Date(a.created_at).getTime():0); }).slice(0,6); setProperties(visibleProperties); setLoading(false); } getProperties(); }, []);
  return <section id="featured-properties" className="bg-[#F8F9FB] py-10 md:py-12"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.25em] text-[#C9A227]">Featured Properties</p><h2 className="mt-1.5 text-2xl font-bold text-[#0A2342]">추천·최근 매물</h2><p className="mt-1 text-sm text-[#0A2342]/60">추천 매물을 먼저, 이후 최근 등록 순으로 안내합니다.</p></div><Link href="/properties" className="inline-flex w-fit rounded-full border border-[#0A2342]/15 bg-white px-4 py-2 text-xs font-semibold">전체 매물 보기 →</Link></div>
  {loading && <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{Array.from({length:6}).map((_,i)=><div key={i} className="animate-pulse overflow-hidden rounded-2xl bg-white"><div className="h-44 bg-[#E7EAF0]" /><div className="h-28 p-4" /></div>)}</div>}
  {!loading && errorMessage && <div className="mt-6 rounded-2xl bg-red-50 p-5 text-center text-sm text-red-700">{errorMessage}</div>}
  {!loading && !errorMessage && properties.length>0 && <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{properties.map((property)=>{ const images=[...(property.property_images||[])].sort((a,b)=>Number(b.is_cover)-Number(a.is_cover)||a.display_order-b.display_order); const coverImage=images[0]?.image_url||property.image_url; const isCompleted=property.listing_status==="completed"; return <Link key={property.id} href={`/properties/${property.id}`} className="group overflow-hidden rounded-2xl border border-[#0A2342]/10 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="relative h-44 overflow-hidden bg-[#EEF1F5]">{coverImage&&<img src={coverImage} alt={property.title} loading="lazy" className={`h-full w-full object-cover transition group-hover:scale-105 ${isCompleted?"grayscale-[35%]":""}`} />}<div className="absolute left-3 top-3 flex gap-1.5">{property.is_featured&&<Badge>추천</Badge>}{isCompleted&&<StatusBadge>계약완료</StatusBadge>}{property.type&&<Badge>{property.type}</Badge>}{property.deal_type&&<Badge>{property.deal_type}</Badge>}</div></div><div className="p-4"><h3 className="line-clamp-2 text-base font-bold text-[#0A2342]">{property.title}</h3><p className="mt-1 line-clamp-1 text-xs text-[#0A2342]/55">{property.location||"지역 문의"}</p><div className="mt-3 flex items-end justify-between gap-2 border-t border-[#0A2342]/10 pt-3"><div><p className="text-xs text-[#0A2342]/50">면적 {property.area||"문의"}</p><p className="mt-0.5 text-base font-bold text-[#C9A227]">{isCompleted?"계약완료":formatPropertyPriceDisplay(property.price)}</p></div><span className="text-xs font-semibold">상세보기 →</span></div></div></Link>;})}</div>}
  {!loading&&!errorMessage&&properties.length===0&&<div className="mt-6 rounded-2xl border border-dashed p-6 text-center text-sm">공개 중인 매물이 없습니다.</div>}</div></section>;
}
function Badge({children}:{children:React.ReactNode}){return <span className="rounded-full bg-white/90 px-2.5 py-1 text-[10px] font-semibold text-[#0A2342] shadow-sm">{children}</span>}
function StatusBadge({children}:{children:React.ReactNode}){return <span className="rounded-full bg-red-600 px-2.5 py-1 text-[10px] font-semibold text-white">{children}</span>}
