"use client";

import { FormEvent, useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Inquiry = { id:number; created_at:string; name:string; phone:string; message:string; property_title:string|null; status:string };

function maskName(name:string){ const v=name.trim(); if(!v)return "고객**"; return `${v.slice(0,1)}${"*".repeat(Math.max(2,v.length-1))}`; }
function maskPhone(phone:string){ const digits=phone.replace(/\D/g,""); if(digits.length<4)return "010-****-****"; return `010-****-${digits.slice(-4)}`; }
function shortText(text:string){ const v=text.replace(/\s+/g," ").trim(); return v.length>24?`${v.slice(0,24)}…`:v; }
function statusInfo(status:string){
 if(status==="completed") return {label:"상담완료",className:"bg-emerald-600"};
 if(status==="in_progress") return {label:"상담중",className:"bg-blue-600"};
 return {label:"문의접수",className:"bg-amber-500"};
}

export default function InquiryBoard(){
 const [slideIndex,setSlideIndex]=useState(0);
 const [name,setName]=useState(""); const [phone,setPhone]=useState(""); const [message,setMessage]=useState(""); const [agreed,setAgreed]=useState(false); const [busy,setBusy]=useState(false); const [result,setResult]=useState(""); const [items,setItems]=useState<Inquiry[]>([]);
 async function load(){ const {data}=await supabase.from("inquiries").select("id,created_at,name,phone,message,property_title,status").order("created_at",{ascending:false}).limit(5); setItems((data??[]) as Inquiry[]); }
 useEffect(()=>{void load(); const channel=supabase.channel("public-inquiry-board").on("postgres_changes",{event:"*",schema:"public",table:"inquiries"},()=>void load()).subscribe(); return()=>{void supabase.removeChannel(channel);};},[]);
 useEffect(()=>{if(items.length<2)return; const timer=window.setInterval(()=>setSlideIndex(i=>(i+1)%items.length),3000); return()=>window.clearInterval(timer);},[items.length]);
 useEffect(()=>{if(slideIndex>=items.length)setSlideIndex(0);},[items.length,slideIndex]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault(); if(!name.trim()||!phone.trim()||!message.trim()){setResult("이름, 연락처, 내용을 입력해 주세요.");return;} if(!agreed){setResult("개인정보 수집·이용에 동의해 주세요.");return;} setBusy(true);setResult(""); try{const response=await fetch("/api/inquiries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:name.trim(),phone:phone.trim(),message:message.trim()})});if(!response.ok)throw new Error("submit");setName("");setPhone("");setMessage("");setAgreed(false);setResult("문의가 접수되었습니다. 담당자가 확인 후 연락드리겠습니다.");await load();}catch{setResult("문의 접수 중 오류가 발생했습니다.");}finally{setBusy(false);} }
 return <section className="bg-[#F8F9FB] px-4 py-7 sm:px-6 md:px-8"><div className="mx-auto grid max-w-7xl gap-4 lg:grid-cols-2"><form onSubmit={submit} className="rounded-2xl border border-[#0A2342]/10 bg-white p-5 shadow-sm"><h2 className="text-lg font-extrabold text-[#0A2342]"><span className="text-[#1769E0]">[매물 문의] [매물 접수]</span> 간편하게 남겨주세요!</h2><p className="mt-1 text-sm font-semibold text-[#0A2342]/65">담당자가 빠르게 연락 드리겠습니다.</p><div className="mt-4 grid grid-cols-2 gap-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="이름" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-[#C9A227]"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="연락처" type="tel" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-[#C9A227]"/></div><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={3} placeholder="찾으시는 매물이나 접수할 매물 내용을 입력해 주세요." className="mt-2 w-full resize-none rounded-xl border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-[#C9A227]"/><label className="mt-2 flex items-center justify-center gap-2 text-xs text-[#0A2342]/70"><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)} className="h-4 w-4"/> 개인정보 수집·이용 동의 <span className="rounded-md border px-2 py-1">문의 처리 목적</span></label><button disabled={busy} className="mt-3 w-full rounded-xl bg-[#1769E0] py-2.5 text-sm font-extrabold text-white disabled:opacity-60">✉ {busy?"접수 중...":"문의하기"}</button>{result&&<p className="mt-2 text-center text-xs text-[#0A2342]/70">{result}</p>}</form><div className="rounded-2xl border border-[#0A2342]/10 bg-white p-3 shadow-sm"><div className="mb-2 flex items-center justify-between px-2"><h3 className="text-sm font-bold text-[#0A2342]">최근 상담 현황</h3><span className="text-[10px] text-[#0A2342]/45">개인정보는 일부 가림 처리됩니다.</span></div><div className="relative h-[238px] overflow-hidden">{items.length?<div className="absolute inset-x-0 transition-transform duration-700 ease-in-out" style={{transform:`translateY(-${slideIndex*58}px)`}}>{[...items,...items].map((item,index)=>{const status=statusInfo(item.status);return <div key={`${item.id}-${index}`} className="mb-2 grid h-[50px] grid-cols-[82px_1fr_auto] items-center gap-3 rounded-xl border border-slate-200 px-3"><span className={`rounded-lg px-2 py-1.5 text-center text-[11px] font-bold text-white ${status.className}`}>{status.label}</span><strong className="min-w-0 truncate text-sm text-[#0A2342]">{shortText(item.property_title&&item.property_title!=="홈페이지 매물 문의"?item.property_title:item.message)}</strong><span className="whitespace-nowrap text-xs font-semibold text-[#0A2342]/65">{maskName(item.name)} ({maskPhone(item.phone)})</span></div>})}</div>:<div className="flex h-full items-center justify-center rounded-xl bg-[#F8F9FB] text-sm text-[#0A2342]/55">접수된 상담 문의가 없습니다.</div>}</div></div></div></section>;
}
