"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Inquiry = { id:number; created_at:string; name:string; phone:string; message:string; property_title:string|null; status:string };

function maskName(name:string){ const v=name.trim(); if(!v)return "고객**"; return `${v.slice(0,1)}${"*".repeat(Math.max(2,v.length-1))}`; }
function maskPhone(phone:string){ const digits=phone.replace(/\D/g,""); if(digits.length<4)return "010-****-****"; return `010-****-${digits.slice(-4)}`; }
function shortText(text:string){ const v=text.replace(/\s+/g," ").trim(); return v.length>24?`${v.slice(0,24)}…`:v; }

export default function InquiryBoard(){
 const [name,setName]=useState(""); const [phone,setPhone]=useState(""); const [message,setMessage]=useState(""); const [agreed,setAgreed]=useState(false); const [busy,setBusy]=useState(false); const [result,setResult]=useState(""); const [items,setItems]=useState<Inquiry[]>([]);
 async function load(){ const {data}=await supabase.from("inquiries").select("id,created_at,name,phone,message,property_title,status").eq("status","completed").order("created_at",{ascending:false}).limit(5); setItems((data??[]) as Inquiry[]); }
 useEffect(()=>{void load();},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault(); if(!name.trim()||!phone.trim()||!message.trim()){setResult("이름, 연락처, 내용을 입력해 주세요.");return;} if(!agreed){setResult("개인정보 수집·이용에 동의해 주세요.");return;} setBusy(true);setResult(""); const {error}=await supabase.from("inquiries").insert({name:name.trim(),phone:phone.trim(),email:null,message:message.trim(),property_title:"홈페이지 매물 문의",status:"new"}); if(error){setResult("문의 접수 중 오류가 발생했습니다.");setBusy(false);return;} setName("");setPhone("");setMessage("");setAgreed(false);setResult("문의가 접수되었습니다. 담당자가 확인 후 연락드리겠습니다.");setBusy(false); }
 const completed=useMemo(()=>items.slice(0,5),[items]);
 return <section className="bg-[#F8F9FB] px-4 py-7 sm:px-6 md:px-8"><div className="mx-auto grid max-w-7xl gap-4 lg:grid-cols-2"><form onSubmit={submit} className="rounded-2xl border border-[#0A2342]/10 bg-white p-5 shadow-sm"><h2 className="text-lg font-extrabold text-[#0A2342]"><span className="text-[#1769E0]">[매물 문의] [매물 접수]</span> 간편하게 남겨주세요!</h2><p className="mt-1 text-sm font-semibold text-[#0A2342]/65">담당자가 빠르게 연락 드리겠습니다.</p><div className="mt-4 grid grid-cols-2 gap-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="이름" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-[#C9A227]"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="연락처" type="tel" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-[#C9A227]"/></div><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={3} placeholder="찾으시는 매물이나 접수할 매물 내용을 입력해 주세요." className="mt-2 w-full resize-none rounded-xl border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-[#C9A227]"/><label className="mt-2 flex items-center justify-center gap-2 text-xs text-[#0A2342]/70"><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)} className="h-4 w-4"/> 개인정보 수집·이용 동의 <span className="rounded-md border px-2 py-1">문의 처리 목적</span></label><button disabled={busy} className="mt-3 w-full rounded-xl bg-[#1769E0] py-2.5 text-sm font-extrabold text-white disabled:opacity-60">✉ {busy?"접수 중...":"문의하기"}</button>{result&&<p className="mt-2 text-center text-xs text-[#0A2342]/70">{result}</p>}</form><div className="rounded-2xl border border-[#0A2342]/10 bg-white p-3 shadow-sm"><div className="mb-2 flex items-center justify-between px-2"><h3 className="text-sm font-bold text-[#0A2342]">최근 상담 현황</h3><span className="text-[10px] text-[#0A2342]/45">개인정보는 일부 가림 처리됩니다.</span></div><div className="grid gap-2">{completed.length?completed.map(item=><div key={item.id} className="grid grid-cols-[82px_1fr_auto] items-center gap-3 rounded-xl border border-slate-200 px-3 py-2.5"><span className="rounded-lg bg-[#0A2342]/55 px-2 py-1.5 text-center text-[11px] font-bold text-white">상담완료</span><strong className="min-w-0 truncate text-sm text-[#0A2342]">{shortText(item.property_title&&item.property_title!=="홈페이지 매물 문의"?item.property_title:item.message)}</strong><span className="whitespace-nowrap text-xs font-semibold text-[#0A2342]/65">{maskName(item.name)} ({maskPhone(item.phone)})</span></div>):<div className="flex min-h-[150px] items-center justify-center rounded-xl bg-[#F8F9FB] text-sm text-[#0A2342]/55">상담 완료 내역이 등록되면 표시됩니다.</div>}</div></div></div></section>;
}
