"use client";

import Script from "next/script";
import { useCallback, useEffect, useRef, useState } from "react";

const OFFICE_NAME = "백조현대부동산중개"; const OFFICE_ADDRESS = "대구광역시 달성군 유가읍 테크노공원로 69"; const OFFICE_DETAIL = "파크뷰타워 105호"; const OFFICE_PHONE = "010-7775-0014"; const FALLBACK_LAT = 35.6939; const FALLBACK_LNG = 128.4598;
type MapStatus = "loading" | "ready" | "error" | "missing-key"; type Coordinates = { latitude:number; longitude:number };
type KakaoMaps = { load:(callback:()=>void)=>void; LatLng:new(latitude:number,longitude:number)=>unknown; Map:new(container:HTMLElement,options:{center:unknown;level:number})=>{setCenter:(position:unknown)=>void;setLevel:(level:number)=>void}; Marker:new(options:{map?:unknown;position:unknown})=>{setMap?:(map:unknown|null)=>void}; MarkerClusterer:new(options:{map:unknown;averageCenter?:boolean;minLevel?:number;disableClickZoom?:boolean;styles?:Array<Record<string,string>>})=>{addMarkers:(markers:unknown[])=>void;clear:()=>void}; InfoWindow:new(options:{content:string})=>{open:(map:unknown,marker:unknown)=>void}; event:{addListener:(target:unknown,type:string,handler:()=>void)=>void}; services:{Status:{OK:string};Geocoder:new()=>{addressSearch:(address:string,callback:(result:Array<{x:string;y:string}>,status:string)=>void)=>void}} };
declare global { interface Window { kakao?: { maps: KakaoMaps } } }

export default function Map(){ const mapContainerRef=useRef<HTMLDivElement>(null); const initializedRef=useRef(false); const appKey=process.env.NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY; const [status,setStatus]=useState<MapStatus>(appKey?"loading":"missing-key"); const [coordinates,setCoordinates]=useState<Coordinates>({latitude:FALLBACK_LAT,longitude:FALLBACK_LNG});
const initializeMap=useCallback(()=>{ if(initializedRef.current)return; const container=mapContainerRef.current; const kakaoMaps=window.kakao?.maps; if(!container||!kakaoMaps)return; initializedRef.current=true; kakaoMaps.load(()=>{try{const fallbackPosition=new kakaoMaps.LatLng(FALLBACK_LAT,FALLBACK_LNG);const map=new kakaoMaps.Map(container,{center:fallbackPosition,level:3});const geocoder=new kakaoMaps.services.Geocoder();geocoder.addressSearch(OFFICE_ADDRESS,(result,searchStatus)=>{if(searchStatus!==kakaoMaps.services.Status.OK||!result[0]){setStatus("error");return;}const latitude=Number(result[0].y),longitude=Number(result[0].x),position=new kakaoMaps.LatLng(latitude,longitude);setCoordinates({latitude,longitude});map.setCenter(position);const marker=new kakaoMaps.Marker({map,position});const infoWindow=new kakaoMaps.InfoWindow({content:'<div style="width:190px;padding:8px;text-align:center;font-size:12px;line-height:1.4;color:#0A2342"><strong>백조현대부동산중개</strong><br/><span style="font-size:11px;color:#666">파크뷰타워 105호</span></div>'});infoWindow.open(map,marker);setStatus("ready");});}catch{setStatus("error");}});},[]);
useEffect(()=>{if(!appKey)return;if(window.kakao?.maps)initializeMap();const timer=window.setTimeout(()=>setStatus(current=>current==="loading"?"error":current),8000);return()=>window.clearTimeout(timer);},[appKey,initializeMap]);
const encodedName=encodeURIComponent(OFFICE_NAME),encodedAddress=encodeURIComponent(`${OFFICE_ADDRESS} ${OFFICE_DETAIL}`),kakaoMapUrl=`https://map.kakao.com/link/search/${encodedAddress}`,directionsUrl=`https://map.kakao.com/link/to/${encodedName},${coordinates.latitude},${coordinates.longitude}`,showInteractiveMap=Boolean(appKey)&&status!=="missing-key"&&status!=="error";
return <section className="bg-white px-5 py-8 md:px-8 md:py-9">{appKey&&<Script id="kakao-map-sdk" src={`https://dapi.kakao.com/v2/maps/sdk.js?appkey=${appKey}&autoload=false&libraries=services,clusterer`} strategy="afterInteractive" onLoad={initializeMap} onReady={initializeMap} onError={()=>setStatus("error")}/>}<div className="mx-auto max-w-7xl"><div className="mb-5 text-center"><p className="text-xs font-semibold tracking-[0.3em] text-[#C9A227]">LOCATION</p><h2 className="mt-1.5 text-2xl font-bold text-[#0A2342]">찾아오시는 길</h2></div><div className="grid gap-4 lg:grid-cols-[2fr_1fr] lg:items-stretch">{showInteractiveMap?<div className="relative h-[280px] overflow-hidden rounded-2xl bg-slate-100 shadow-md lg:h-[300px]"><div ref={mapContainerRef} className="h-full w-full"/>{status==="loading"&&<div className="absolute inset-0 flex items-center justify-center bg-slate-100 text-sm font-semibold text-[#0A2342]/70">카카오맵을 불러오는 중입니다.</div>}</div>:<div className="flex min-h-[280px] items-center justify-center rounded-2xl border border-[#0A2342]/10 bg-[#F8F9FB] px-5 py-5 text-center shadow-sm lg:min-h-[300px]"><div><p className="font-bold text-[#0A2342]">{OFFICE_ADDRESS} {OFFICE_DETAIL}</p><a href={kakaoMapUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex rounded-full bg-[#C9A227] px-4 py-2 text-xs font-bold text-[#0A2342]">카카오맵에서 위치 확인하기</a></div></div>}<div className="flex min-h-[280px] flex-col justify-center rounded-2xl bg-[#0A2342] p-5 text-white lg:min-h-[300px]"><p className="text-[10px] font-semibold tracking-[.22em] text-[#C9A227]">OFFICE</p><h3 className="mt-2 text-lg font-bold">{OFFICE_NAME}</h3><p className="mt-3 text-sm leading-6 text-white/75">{OFFICE_ADDRESS}<br/>{OFFICE_DETAIL}</p><a href="tel:01077750014" className="mt-3 inline-block text-sm font-bold text-[#E1B723]">☎ {OFFICE_PHONE}</a><div className="mt-5 grid gap-2"><a href={directionsUrl} target="_blank" rel="noreferrer" className="rounded-lg bg-[#C9A227] px-4 py-2.5 text-center text-sm font-semibold text-[#0A2342]">길찾기</a><a href={kakaoMapUrl} target="_blank" rel="noreferrer" className="rounded-lg border border-white/30 px-4 py-2.5 text-center text-sm font-semibold text-white">카카오맵에서 보기</a></div></div></div></div></section>;
}
