const fallbackUrl = "https://premium-estate-rho.vercel.app";

export const siteConfig = {
  name: "백조현대부동산중개",
  representative: "하순영",
  title: "현풍·유가읍 부동산 | 원룸·투룸·상가 | 백조현대부동산",
  description:
    "대구 달성군 현풍읍·유가읍·대구테크노폴리스·디지스트(DGIST) 인근 원룸·미니투룸·투룸·상가·아파트·창고·공장·토지 매물을 확인하세요. 백조현대부동산중개가 실제 등록 매물을 안내합니다.",
  url: (process.env.NEXT_PUBLIC_SITE_URL || fallbackUrl).replace(/\/$/, ""),
  ogImage: "/opengraph-image",
  phone: process.env.NEXT_PUBLIC_BUSINESS_PHONE || "",
  address: process.env.NEXT_PUBLIC_BUSINESS_ADDRESS || "",
  serviceAreas: [
    "대구광역시 달성군",
    "유가읍",
    "현풍읍",
    "구지면",
    "대구테크노폴리스",
    "디지스트(DGIST)",
    "창녕군",
  ],
  keywords: [
    "현풍 부동산",
    "현풍읍 부동산",
    "유가읍 부동산",
    "대구테크노폴리스 부동산",
    "디지스트 부동산",
    "현풍 원룸",
    "현풍 투룸",
    "유가읍 원룸",
    "유가읍 투룸",
    "대구테크노폴리스 원룸",
    "대구테크노폴리스 투룸",
    "디지스트 원룸",
    "디지스트 미니투룸",
    "디지스트 투룸",
    "구지면 부동산",
    "달성군 상가 임대",
    "달성군 상가 매매",
    "달성군 아파트",
    "달성군 창고",
    "달성군 공장",
    "달성군 토지",
    "백조현대부동산",
    "백조현대부동산중개",
  ],
} as const;
