import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { ADMIN_COOKIE_NAME, isValidAdminSession } from "@/lib/admin-session";
export const runtime="nodejs";
const BUCKET="property-images",STORAGE_PATH="admin-data/building-directory.json";
const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL,serviceRoleKey=process.env.SUPABASE_SERVICE_ROLE_KEY;
type BuildingRow={buildingName:string;town:string;village:string;lot:string;address:string;approvalDate:string;zone:string;phone:string;vacancy:string;commercial:string;entrance:string;owner:string};
async function requireAdmin(r:NextRequest){return isValidAdminSession(r.cookies.get(ADMIN_COOKIE_NAME)?.value)}
function client(){return supabaseUrl&&serviceRoleKey?createClient(supabaseUrl,serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false}}):null}
const text=(v:unknown)=>String(v??"").trim();
function sanitizeRows(value:unknown):BuildingRow[]{if(!Array.isArray(value))return[];const seen=new Set<string>(),rows:BuildingRow[]=[];for(const item of value){if(!item||typeof item!=="object")continue;const s=item as Record<string,unknown>;const row={buildingName:text(s.buildingName),town:text(s.town),village:text(s.village),lot:text(s.lot),address:text(s.address),approvalDate:text(s.approvalDate),zone:text(s.zone),phone:text(s.phone),vacancy:text(s.vacancy),commercial:text(s.commercial),entrance:text(s.entrance),owner:text(s.owner)};if(!row.buildingName&&!row.address)continue;const key=`${row.buildingName}|${row.address}`;if(seen.has(key))continue;seen.add(key);rows.push(row)}return rows}
export async function GET(request:NextRequest){if(!(await requireAdmin(request)))return NextResponse.json({ok:false,error:"Unauthorized"},{status:401});const s=client();if(!s)return NextResponse.json({ok:false,error:"Supabase server configuration is missing."},{status:500});const{data,error}=await s.storage.from(BUCKET).download(STORAGE_PATH);if(error){if(/not found|object not found/i.test(error.message))return NextResponse.json({ok:true,rows:[]});return NextResponse.json({ok:false,error:error.message},{status:500})}try{return NextResponse.json({ok:true,rows:sanitizeRows(JSON.parse(await data.text()))})}catch{return NextResponse.json({ok:false,error:"Saved building directory is invalid."},{status:500})}}
export async function POST(request:NextRequest){if(!(await requireAdmin(request)))return NextResponse.json({ok:false,error:"Unauthorized"},{status:401});const s=client();if(!s)return NextResponse.json({ok:false,error:"Supabase server configuration is missing."},{status:500});let body:{rows?:unknown};try{body=await request.json()}catch{return NextResponse.json({ok:false,error:"Invalid JSON."},{status:400})}const rows=sanitizeRows(body.rows);if(!rows.length)return NextResponse.json({ok:false,error:"저장할 장부 정보가 없습니다."},{status:400});const payload=Buffer.from(JSON.stringify(rows),"utf-8");const{error}=await s.storage.from(BUCKET).upload(STORAGE_PATH,payload,{upsert:true,contentType:"application/json;charset=utf-8"});if(error)return NextResponse.json({ok:false,error:error.message},{status:500});return NextResponse.json({ok:true,count:rows.length})}
