"use client";

import { useEffect, useMemo, useState } from "react";

type Contact={id:number;property_id:number;contact_name?:string|null;phone:string;enabled:boolean;last_called_at?:string|null;last_checked_at?:string|null;next_check_at?:string|null;last_result?:string|null;last_note?:string|null};
type Property={id:number;title:string;location?:string|null;price?:string|null;is_hidden?:boolean;listing_status?:string|null};
type Data={ok:boolean;configured?:boolean;setupNeeded?:boolean;error?:string;contacts?:Contact[];properties?:Property[]};
const labels:Record<string,string>={available:"거래 가능",completed:"거래 완료",changed:"조건 변경",retry:"재통화 필요",unknown:"확인 필요"};
const fmt=(v?:string|null)=>v?new Date(v).toLocaleString("ko-KR"):"-";

export default function PropertyCallsPage(){
 const[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[propertyId,setPropertyId]=useState(""),[contactName,setContactName]=useState(""),[phone,setPhone]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/property-calls",{cache:"no-store"});setData(await r.json())}catch{setData({ok:false,error:"자동전화 현황을 불러오지 못했습니다."})}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const propertyMap=useMemo(()=>new Map((data?.properties||[]).map(p=>[p.id,p])),[data]);
 async function add(){if(!propertyId||!phone)return alert("매물과 전화번호를 입력해 주세요.");setBusy(true);try{const r=await fetch("/api/admin/property-calls",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({propertyId:Number(propertyId),contactName,phone})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"등록 실패");setContactName("");setPhone("");await load()}catch(e){alert(e instanceof Error?e.message:"등록 실패")}finally{setBusy(false)}}
 async function toggle(c:Contact){setBusy(true);try{await fetch("/api/admin/property-calls",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:c.id,enabled:!c.enabled})});await load()}finally{setBusy(false)}}
 async function runNow(){if(!confirm("현재 확인 대상 매물에 자동전화를 시작할까요?"))return;setBusy(true);try{const r=await fetch("/api/property-calls/run",{method:"POST"});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"실행 실패");alert(`자동전화 ${j.attempted}건 확인 · 발신 성공 ${j.success}건`);await load()}catch(e){alert(e instanceof Error?e.message:"실행 실패")}finally{setBusy(false)}}
 return <main className="min-h-screen bg-[#F8F9FB] px-4 py-8 text-[#0A2342]"><div className="mx-auto max-w-7xl rounded-[28px] bg-white p-6 shadow-sm md:p-8">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold tracking-[.24em] text-[#C9A227]">WEEKLY PROPERTY CHECK</p><h1 className="mt-1 text-3xl font-bold">주간 매물 확인 자동전화</h1><p className="mt-2 text-sm text-[#0A2342]/60">임대인·매도인에게 주 1회 확인 전화를 걸고 키패드 응답을 자동 기록합니다.</p></div><button disabled={busy||!data?.configured} onClick={()=>void runNow()} className="rounded-xl bg-[#0A2342] px-5 py-3 text-sm font-bold text-white disabled:opacity-40">지금 확인전화 실행</button></div>
  {loading?<p className="py-12 text-center">불러오는 중입니다...</p>:!data?.ok?<div className="mt-6 rounded-2xl bg-amber-50 p-5 text-sm leading-6"><b>초기 설정이 필요합니다.</b><br/>{data?.error||"데이터베이스 또는 전화 서비스 설정을 확인해 주세요."}{data?.setupNeeded&&<><br/>저장소의 <code>supabase/property_call_setup.sql</code>을 Supabase에서 1회 실행해야 합니다.</>}</div>:<>
   {!data.configured&&<div className="mt-6 rounded-2xl bg-blue-50 p-5 text-sm leading-6"><b>전화 발신 연결 전 단계입니다.</b><br/>Twilio 발신번호와 인증 환경변수를 Vercel에 연결하면 실제 자동발신이 활성화됩니다. 현재는 대상 등록과 관리가 가능합니다.</div>}
   <section className="mt-6 rounded-2xl border p-5"><h2 className="text-lg font-bold">확인 대상 추가</h2><div className="mt-4 grid gap-3 md:grid-cols-[1.5fr_1fr_1fr_auto]"><select value={propertyId} onChange={e=>setPropertyId(e.target.value)} className="rounded-xl border px-4 py-3"><option value="">매물 선택</option>{(data.properties||[]).filter(p=>!p.is_hidden&&p.listing_status!=="completed").map(p=><option key={p.id} value={p.id}>#{p.id} {p.title}</option>)}</select><input value={contactName} onChange={e=>setContactName(e.target.value)} placeholder="연락처 이름(선택)" className="rounded-xl border px-4 py-3"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="010-0000-0000" className="rounded-xl border px-4 py-3"/><button disabled={busy} onClick={()=>void add()} className="rounded-xl bg-[#C9A227] px-5 py-3 font-bold">추가</button></div></section>
   <section className="mt-6 overflow-x-auto rounded-2xl border"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-[#F8F9FB]"><tr>{["매물","연락처","상태","최근 확인","다음 확인","최근 결과","관리"].map(v=><th key={v} className="px-4 py-3 text-left">{v}</th>)}</tr></thead><tbody>{(data.contacts||[]).map(c=>{const p=propertyMap.get(c.property_id);return <tr key={c.id} className="border-t"><td className="px-4 py-3"><b>#{c.property_id} {p?.title||"매물"}</b><div className="text-xs text-[#0A2342]/50">{p?.location||""} {p?.price||""}</div></td><td className="px-4 py-3">{c.contact_name||"-"}<div className="text-xs">{c.phone}</div></td><td className="px-4 py-3">{c.enabled?"자동확인 중":"중지"}</td><td className="px-4 py-3">{fmt(c.last_checked_at)}</td><td className="px-4 py-3">{fmt(c.next_check_at)}</td><td className="px-4 py-3 font-semibold">{c.last_result?labels[c.last_result]||c.last_result:"-"}</td><td className="px-4 py-3"><button disabled={busy} onClick={()=>void toggle(c)} className="rounded-full border px-3 py-1 text-xs font-semibold">{c.enabled?"자동확인 중지":"자동확인 재개"}</button></td></tr>})}{!(data.contacts||[]).length&&<tr><td colSpan={7} className="px-4 py-10 text-center text-[#0A2342]/50">등록된 확인 대상이 없습니다.</td></tr>}</tbody></table></section>
  </>}
 </div></main>
}
