create table if not exists public.collected_listings (
  id bigint generated by default as identity primary key,
  source text not null,
  source_listing_id text not null,
  source_url text,
  title text not null,
  location text,
  address text,
  property_type text,
  deal_type text,
  price_text text,
  deposit_text text,
  monthly_rent_text text,
  area_text text,
  floor_text text,
  description text,
  image_urls jsonb not null default '[]'::jsonb,
  fingerprint text,
  duplicate_of text,
  review_status text not null default 'pending',
  raw_payload jsonb,
  collected_at timestamptz not null default now(),
  reviewed_at timestamptz,
  created_property_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint collected_listings_source_listing_unique unique (source, source_listing_id),
  constraint collected_listings_review_status_check
    check (review_status in ('pending', 'approved', 'rejected'))
);

create index if not exists collected_listings_review_status_idx
  on public.collected_listings (review_status, collected_at desc);

create index if not exists collected_listings_fingerprint_idx
  on public.collected_listings (fingerprint);

comment on table public.collected_listings is '외부 플랫폼에서 자동 수집한 매물의 관리자 검토대기 큐';
comment on column public.collected_listings.source is 'naver, realestatebank, hanbang 등 원본 플랫폼';
comment on column public.collected_listings.source_listing_id is '원본 플랫폼 매물번호';
comment on column public.collected_listings.review_status is 'pending, approved, rejected';
comment on column public.collected_listings.created_property_id is '승인 후 생성된 properties.id';
