"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";
import { buildDescriptionWithAdminMeta, parseAdminMeta } from "@/lib/property-admin-meta";

type Item={id:number;title:string;address?:string|null;location?:string|null;type?:string|null;description?:string|null};
type Status="대기"|"완료"|"건너뜀"|"실패";
type RowResult={id:number;status:Status;message?:string};
type StatusFilter="전체"|Status;

type LedgerData={buildingName?:string;buildingUse?:string;approvalDate?:string;totalFloor?:string|number;undergroundFloor?:string|number;parkingCount?:string|number;totalArea?:string|number;floorArea?:string|number;landArea?:string|number;structure?:string;mainPurpose?:string;roadAddress?:string;jibunAddress?:string;householdCount?:string|number;unitCount?:string|number;coverageRatio?:string|number;floorAreaRatio?:string|number;[key:string]:unknown};

function lookupGuide(type:string){if(/상가주택|단독주택|다가구/.test(type))return "건물 통매매/통임대: 정확한 지번만 입력";if(/아파트|오피스텔|다세대|연립|빌라/.test(type))return "지번 + 동/호수 입력";if(/상가|사무실/.test(type))return "개별 호실 매물: 지번 + 호수 입력";if(/원룸|미니투룸|투룸|쓰리룸/.test(type))return "정확한 지번 입력";return "건축물대장 조회용 정확한 지번 입력";}
function restoredLedgerResult(item:Item):RowResult|undefined{const meta=parseAdminMeta(item.description||"");if(/^조회 실패/.test(meta.ledgerSummary||"")||/전유부 재확인 필요|전용면적 기존 정보 유지/.test(meta.ledgerSummary||""))return{id:item.id,status:"실패",message:meta.ledgerSummary||"건축물대장 조회 실패"};const legacyCompleted=Boolean(meta.infoOverrides?.buildingUse&&meta.infoOverrides?.approvalDate);if(meta.ledgerStatus==="completed"||legacyCompleted){const fallback=[meta.infoOverrides?.buildingUse,meta.infoOverrides?.approvalDate,meta.infoOverrides?.parking].filter(Boolean).join(" · ");return{id:item.id,status:"완료",message:meta.ledgerSummary||fallback||"건축물대장 등록 완료"};}return undefined;}
const statusStyle:Record<Status,string>={"대기":"border-slate-200 bg-slate-50 text-slate-700","완료":"border-blue-200 bg-blue-50 text-blue-700","실패":"border-red-200 bg-red-50 text-red-700","건너뜀":"border-amber-200 bg-amber-50 text-amber-700"};

function esc(value:unknown){return String(value??"").replace(/[&<>\"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[ch]||ch));}
function printableRows(ledger:LedgerData){return [["건물명",ledger.buildingName],["주용도",ledger.buildingUse||ledger.mainPurpose],["구조",ledger.structure],["사용승인일",ledger.approvalDate],["지상층수",ledger.totalFloor],["지하층수",ledger.undergroundFloor],["대지면적",ledger.landArea],["건축면적",ledger.floorArea],["연면적",ledger.totalArea],["건폐율",ledger.coverageRatio],["용적률",ledger.floorAreaRatio],["주차대수",ledger.parkingCount],["세대수",ledger.householdCount],["호수",ledger.unitCount]].filter(([,v])=>v!==undefined&&v!==null&&String(v).trim()!=="");}
function renderPrint(win:Window,item:Item,address:string,ledger:LedgerData,summary:string){const rows=printableRows(ledger).map(([k,v])=>`<tr><th>${esc(k)}</th><td>${esc(v)}</td></tr>`).join("");win.document.open();win.document.write(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>건축물대장 조회표 - ${esc(item.title)}</title><style>@page{size:A4;margin:14mm}*{box-sizing:border-box}body{font-family:Arial,'Noto Sans KR',sans-serif;color:#111;margin:0}h1{font-size:24px;margin:0 0 8px}.sub{color:#555;font-size:12px;margin-bottom:18px}.notice{padding:10px 12px;background:#f5f5f5;border:1px solid #ddd;font-size:11px;margin-bottom:16px}table{width:100%;border-collapse:collapse;font-size:13px}th,td{border:1px solid #999;padding:8px 10px;text-align:left;vertical-align:top}th{width:28%;background:#f7f7f7}h2{font-size:15px;margin:18px 0 8px}.summary{border:1px solid #999;padding:10px;font-size:13px}.footer{margin-top:18px;font-size:10px;color:#666}.no-print{margin:16px 0;text-align:right}.no-print button{padding:10px 16px;font-weight:700}@media print{.no-print{display:none}}</style></head><body><div class="no-print"><button onclick="window.print()">인쇄</button></div><h1>건축물대장 조회표</h1><div class="sub">매물번호 ${esc(item.id)} · ${esc(item.title)} · 조회일 ${new Date().toLocaleDateString("ko-KR")}</div><div class="notice">본 문서는 건축물대장 API 조회정보를 관리자 업무용으로 정리한 출력물이며, 관공서 제출용 공식 발급본은 아닙니다.</div><table><tr><th>조회주소</th><td>${esc(address)}</td></tr><tr><th>홈페이지 표시주소</th><td>${esc(item.address||item.location||"")}</td></tr>${rows}</table><h2>조회 요약</h2><div class="summary">${esc(summary||"조회 완료")}</div><div class="footer">백조현대부동산 관리자 · 공식 발급본이 필요한 경우 세움터/정부24 발급 절차를 이용하세요.</div><script>window.onload=function(){setTimeout(function(){window.print()},250)}<\/script></body></html>`);win.document.close();}

export default function BuildingLedgerAdminPage(){
 const[items,setItems]=useState<Item[]>([]),[results,setResults]=useState<Record<number,RowResult>>({}),[drafts,setDrafts]=useState<Record<number,string>>({});const[selected,setSelected]=useState<Set<number>>(new Set());const[searchKeyword,setSearchKeyword]=useState(""),[statusFilter,setStatusFilter]=useState<StatusFilter>("전체");const[running,setRunning]=useState(false),[savingId,setSavingId]=useState<number|null>(null),[savingSelected,setSavingSelected]=useState(false);
 useEffect(()=>{void load();},[]);
 async function load(){const{data}=await supabase.from("properties").select("id,title,address,location,type,description").order("id",{ascending:false});const rows=(data||[]) as Item[];setItems(rows);const nd:Record<number,string>={},nr:Record<number,RowResult>={};for(const item of rows){const meta=parseAdminMeta(item.description||"");nd[item.id]=meta.ledgerLookupAddress||"";const restored=restoredLedgerResult(item);if(restored)nr[item.id]=restored;}setDrafts(nd);setResults(nr);}
 const statusOf=(item:Item):Status=>results[item.id]?.status||"대기";
 const counts=useMemo(()=>{const c:Record<Status,number>={"대기":0,"완료":0,"실패":0,"건너뜀":0};items.forEach(v=>c[results[v.id]?.status||"대기"]++);return c;},[items,results]);
 const filteredItems=useMemo(()=>{const q=searchKeyword.trim().toLowerCase();return items.filter(item=>{if(statusFilter!=="전체"&&(results[item.id]?.status||"대기")!==statusFilter)return false;if(!q)return true;const meta=parseAdminMeta(item.description||"");return[String(item.id),item.title,item.type,item.address,item.location,meta.ledgerLookupAddress,drafts[item.id]].filter(Boolean).join(" ").toLowerCase().includes(q);});},[items,searchKeyword,drafts,statusFilter,results]);
 const allSelected=useMemo(()=>filteredItems.length>0&&filteredItems.every(v=>selected.has(v.id)),[filteredItems,selected]);function toggleAll(){setSelected(prev=>{const next=new Set(prev);if(allSelected)filteredItems.forEach(v=>next.delete(v.id));else filteredItems.forEach(v=>next.add(v.id));return next;});}function toggleOne(id:number){setSelected(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);return next;});}
 async function saveLookupAddress(item:Item,address:string){const value=address.trim(),meta=parseAdminMeta(item.description||"");if(meta.ledgerLookupAddress===value)return true;setSavingId(item.id);const nextMeta={...meta,ledgerLookupAddress:value,ledgerStatus:"" as const,ledgerSummary:"",ledgerUpdatedAt:""};const description=buildDescriptionWithAdminMeta(item.description||"",nextMeta);const{error}=await supabase.from("properties").update({description}).eq("id",item.id);setSavingId(null);if(error){window.alert("관리자 전용 조회주소 저장에 실패했습니다.");return false;}setItems(list=>list.map(v=>v.id===item.id?{...v,description}:v));setResults(prev=>{const next={...prev};delete next[item.id];return next;});return true;}
 async function saveSelectedAddresses(){if(savingSelected||running||!selected.size)return;setSavingSelected(true);let saved=0,failed=0;for(const item of items.filter(v=>selected.has(v.id))){(await saveLookupAddress(item,drafts[item.id]||""))?saved++:failed++;}setSavingSelected(false);window.alert(failed?`조회주소 저장 완료: ${saved}건 / 실패: ${failed}건`:`선택한 ${saved}개 매물의 조회주소를 저장했습니다.`);}
 async function persistFailure(item:Item,message:string){const current=items.find(v=>v.id===item.id)||item,meta=parseAdminMeta(current.description||"");const nextMeta={...meta,ledgerStatus:"" as const,ledgerSummary:`조회 실패 · ${message}`,ledgerUpdatedAt:new Date().toISOString()};const description=buildDescriptionWithAdminMeta(current.description||"",nextMeta);const{error}=await supabase.from("properties").update({description}).eq("id",item.id);if(!error)setItems(list=>list.map(v=>v.id===item.id?{...v,description}:v));}
 async function enrich(item:Item,printWindow?:Window|null){const adminAddress=(drafts[item.id]||"").trim(),publicAddress=(item.address||item.location||"").trim(),address=adminAddress||publicAddress;if(!address){printWindow?.close();setResults(p=>({...p,[item.id]:{id:item.id,status:"건너뜀",message:"조회주소 없음"}}));return;}if(adminAddress&&!(await saveLookupAddress(item,adminAddress))){printWindow?.close();return;}setResults(p=>({...p,[item.id]:{id:item.id,status:"대기",message:"조회 중"}}));try{const r=await fetch("/api/admin/building-ledger",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({property_id:item.id,address})});const data=await r.json();if(!data.ok)throw new Error([data.error,data.detail].filter(Boolean).join(" · ")||"조회 실패");const l=(data.ledger||{}) as LedgerData,msg=data.summary||[l.buildingUse,l.approvalDate,l.totalFloor?`지상 ${l.totalFloor}층`:"",l.parkingCount?`주차 ${l.parkingCount}대`:""].filter(Boolean).join(" · ");if(data.partial||data.warning||/전유부 재확인 필요|전용면적 기존 정보 유지/.test(msg||"")){const failMsg=data.warning||msg||"전유부 조회 실패";printWindow?.close();setResults(p=>({...p,[item.id]:{id:item.id,status:"실패",message:failMsg}}));await persistFailure(item,failMsg);return;}setResults(p=>({...p,[item.id]:{id:item.id,status:"완료",message:msg||"보완 완료"}}));if(data.description)setItems(list=>list.map(v=>v.id===item.id?{...v,description:data.description}:v));if(printWindow)renderPrint(printWindow,item,address,l,msg||"조회 완료");}catch(e){printWindow?.close();const m=e instanceof Error?e.message:String(e);setResults(p=>({...p,[item.id]:{id:item.id,status:"실패",message:m}}));await persistFailure(item,m);}}
 function lookupAndPrint(item:Item){const w=window.open("","_blank","width=900,height=1100");if(!w){window.alert("팝업이 차단되어 있습니다. 이 사이트의 팝업을 허용한 뒤 다시 눌러주세요.");return;}w.document.write("<p style='font-family:sans-serif;padding:24px'>건축물대장을 조회하고 있습니다...</p>");void enrich(item,w);}
 async function runSelected(){if(running||savingSelected||!selected.size)return;setRunning(true);for(const item of items.filter(v=>selected.has(v.id)))await enrich(item);setRunning(false);}async function runAll(){if(running||savingSelected)return;setRunning(true);for(const item of items)await enrich(item);setRunning(false);}
 return <main className="min-h-screen bg-[#F8F9FB] px-4 py-8 text-[#0A2342]"><div className="mx-auto max-w-[1480px] rounded-[32px] bg-white p-6 shadow-sm md:p-8">
 <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold">건축물대장 조회·출력</h1><p className="mt-2 text-sm text-[#0A2342]/60">주소로 건축물대장을 조회해 매물정보를 보완하고, 조회 결과를 A4로 바로 출력합니다.</p></div><div className="flex gap-2"><Link href="/admin" className="rounded-full border px-5 py-3">매물관리</Link><button onClick={()=>void runAll()} disabled={running||savingSelected} className="rounded-full bg-[#C9A227] px-5 py-3 font-semibold disabled:opacity-50">{running?"조회 중...":"전체 매물 보완"}</button></div></div>
 <div className="sticky top-2 z-40 mt-6 rounded-2xl border border-[#0A2342]/15 bg-white/95 p-3 shadow-[0_10px_30px_rgba(10,35,66,0.12)] backdrop-blur"><div className="flex flex-wrap items-center gap-2 border-b pb-3"><button onClick={()=>setStatusFilter("전체")} className={`rounded-xl border px-4 py-2 text-sm font-bold ${statusFilter==="전체"?"border-[#0A2342] bg-[#0A2342] text-white":"bg-white"}`}>전체 {items.length}</button>{(["대기","완료","실패","건너뜀"] as Status[]).map(s=><button key={s} onClick={()=>setStatusFilter(s)} className={`rounded-xl border px-4 py-2 text-sm font-bold ${statusFilter===s?statusStyle[s]+" ring-2 ring-offset-1":"bg-white"}`}><span className={`mr-2 inline-block h-2.5 w-2.5 rounded-full ${s==="완료"?"bg-blue-500":s==="실패"?"bg-red-500":s==="건너뜀"?"bg-amber-500":"bg-slate-400"}`}/>{s} {counts[s]}</button>)}</div><div className="flex flex-wrap items-center gap-3 pt-3"><label className="flex items-center gap-2 font-semibold"><input type="checkbox" checked={allSelected} onChange={toggleAll} className="h-5 w-5"/>전체 선택</label><span className="text-sm">선택 <b className="rounded-full bg-[#0A2342] px-3 py-1 text-white">{selected.size}개</b></span><input value={searchKeyword} onChange={e=>setSearchKeyword(e.target.value)} placeholder="매물번호·매물명·주소 검색" className="min-w-[240px] flex-1 rounded-xl border px-4 py-2.5 text-sm md:max-w-[360px]"/><button onClick={()=>void saveSelectedAddresses()} disabled={running||savingSelected||!selected.size} className="rounded-xl border border-[#0A2342] bg-white px-5 py-2.5 font-semibold disabled:opacity-40">조회주소 저장</button><button onClick={()=>void runSelected()} disabled={running||savingSelected||!selected.size} className="rounded-xl bg-[#0A2342] px-5 py-2.5 font-semibold text-white disabled:opacity-40">선택 매물 보완</button><button onClick={()=>setSelected(new Set())} disabled={!selected.size} className="rounded-xl border bg-white px-5 py-2.5 font-semibold disabled:opacity-40">선택 초기화</button></div></div>
 <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1360px]"><thead className="bg-[#F8F9FB]"><tr><th className="w-12 px-3 py-4 text-left"><input type="checkbox" checked={allSelected} onChange={toggleAll} className="h-5 w-5"/></th>{["번호","매물명","유형","건축물대장 조회주소 (관리자 전용)","홈페이지 표시주소","처리상태","관리"].map(v=><th key={v} className="px-3 py-4 text-left">{v}</th>)}</tr></thead><tbody>{filteredItems.map(item=>{const result=results[item.id],type=item.type||"-",publicAddress=item.address||item.location||"주소 없음",status=statusOf(item);return <tr key={item.id} className={`border-t align-top text-sm ${status==="실패"?"bg-red-50/40":status==="완료"?"bg-blue-50/20":""}`}><td className="px-3 py-4"><input type="checkbox" checked={selected.has(item.id)} onChange={()=>toggleOne(item.id)} className="h-5 w-5"/></td><td className="px-3 py-4 font-semibold">{item.id}</td><td className="px-3 py-4 font-semibold"><Link href={`/admin/properties/${item.id}/edit`} target="_blank" rel="noopener noreferrer" className="underline decoration-dotted underline-offset-4 hover:text-[#C9A227]">{item.title}</Link></td><td className="px-3 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{type}</span></td><td className="min-w-[330px] px-3 py-4"><input value={drafts[item.id]||""} onChange={e=>setDrafts(p=>({...p,[item.id]:e.target.value}))} onBlur={()=>void saveLookupAddress(item,drafts[item.id]||"")} placeholder={lookupGuide(type)} className="w-full rounded-xl border px-3 py-2.5"/><p className="mt-1.5 text-xs text-[#0A2342]/55">{lookupGuide(type)} · 관리자만 확인</p></td><td className="min-w-[230px] px-3 py-4">{publicAddress}</td><td className="min-w-[220px] px-3 py-4"><span className={`inline-flex rounded-full border px-3 py-1 text-xs font-bold ${statusStyle[status]}`}>{status}</span>{result?.message&&<p className="mt-2 max-w-[300px] break-words text-xs text-[#0A2342]/60">{result.message}</p>}</td><td className="min-w-[205px] px-3 py-4"><div className="flex flex-wrap gap-2"><button onClick={()=>void enrich(item)} disabled={running||savingSelected||savingId===item.id} className="rounded-full border px-4 py-2 font-semibold disabled:opacity-40">{savingId===item.id?"저장 중...":"조회"}</button><button onClick={()=>lookupAndPrint(item)} disabled={running||savingSelected||savingId===item.id} className="rounded-full bg-[#C9A227] px-4 py-2 font-semibold text-[#0A2342] disabled:opacity-40">조회·출력</button></div></td></tr>})}</tbody></table></div>
 {!filteredItems.length&&<div className="rounded-2xl border border-dashed p-10 text-center text-sm text-[#0A2342]/60">해당 처리상태의 매물이 없습니다.</div>}
 </div></main>;
}
