"use client";

import { useEffect, useMemo, useState, type ChangeEvent } from "react";
import * as XLSX from "xlsx";

type LedgerRow = { id:string; area:string; buildingName:string; lot:string; owner:string; vacancy:string; phones:string[] };
const LOCAL_KEY="baekjo_vacancy_sms_ledger_v1";
const DEFAULT_MESSAGE="백조현대부동산입니다. {건물명} 현재 공실 있으면 보증금/월세와 입주가능일 회신 부탁드립니다.";
const text=(v:unknown)=>v==null?"":String(v).trim();
function normalizePhone(v:string){const d=v.replace(/\D/g,"");return d.length===10||d.length===11?d:""}
function extractPhones(v:unknown){return Array.from(new Set((text(v).match(/01[016789][\s-]?\d{3,4}[\s-]?\d{4}/g)||[]).map(normalizePhone).filter(Boolean)))}
function displayPhone(v:string){return v.length===11?`${v.slice(0,3)}-${v.slice(3,7)}-${v.slice(7)}`:v.length===10?`${v.slice(0,3)}-${v.slice(3,6)}-${v.slice(6)}`:v}
function parseWorkbook(workbook:XLSX.WorkBook){const rows:LedgerRow[]=[];for(const sheetName of workbook.SheetNames){const sheet=workbook.Sheets[sheetName];if(!sheet)continue;const values=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,defval:"",raw:false});const hi=values.findIndex(r=>Array.isArray(r)&&r.some(v=>["건 물 명","건물명"].includes(text(v))));if(hi<0)continue;const h=values[hi].map(v=>text(v).replace(/\s/g,""));const col=(n:string)=>h.findIndex(v=>v===n.replace(/\s/g,""));const bc=Math.max(col("건물명"),0),lc=col("주소"),oc=col("소유자"),vc=col("공실"),pc=col("전화번호");for(let i=hi+1;i<values.length;i++){const r=values[i]||[],buildingName=text(r[bc]);if(!buildingName)continue;rows.push({id:`${sheetName}-${i}-${buildingName}`,area:sheetName,buildingName,lot:lc>=0?text(r[lc]):"",owner:oc>=0?text(r[oc]):"",vacancy:vc>=0?text(r[vc]):"",phones:pc>=0?extractPhones(r[pc]):[]})}}return rows}
export default function VacancySmsPage(){
 const[rows,setRows]=useState<LedgerRow[]>([]),[selected,setSelected]=useState<Set<string>>(new Set());const[keyword,setKeyword]=useState(""),[area,setArea]=useState("전체"),[messageTemplate,setMessageTemplate]=useState(DEFAULT_MESSAGE),[status,setStatus]=useState("");
 useEffect(()=>{try{const s=localStorage.getItem(LOCAL_KEY);if(s)setRows(JSON.parse(s))}catch{}},[]);
 async function handleExcel(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];e.target.value="";if(!f)return;setStatus("장부를 읽는 중입니다...");try{const w=XLSX.read(await f.arrayBuffer(),{type:"array",cellDates:true}),imported=parseWorkbook(w);setRows(imported);setSelected(new Set());localStorage.setItem(LOCAL_KEY,JSON.stringify(imported));setStatus(`${imported.length}개 건물을 읽었습니다. 전화번호가 있는 건물 ${imported.filter(r=>r.phones.length).length}개입니다.`)}catch{setStatus("엑셀 장부를 읽지 못했습니다.")}}
 const areas=useMemo(()=>["전체",...Array.from(new Set(rows.map(r=>r.area)))],[rows]);const filtered=useMemo(()=>{const q=keyword.trim().toLowerCase();return rows.filter(r=>(area==="전체"||r.area===area)&&(!q||[r.area,r.buildingName,r.lot,r.owner,r.vacancy,...r.phones].join(" ").toLowerCase().includes(q)))},[rows,area,keyword]);const selectable=filtered.filter(r=>r.phones.length),allSelected=selectable.length>0&&selectable.every(r=>selected.has(r.id));
 function toggleAll(){setSelected(p=>{const n=new Set(p);if(allSelected)selectable.forEach(r=>n.delete(r.id));else selectable.forEach(r=>n.add(r.id));return n})}function toggleOne(id:string){setSelected(p=>{const n=new Set(p);n.has(id)?n.delete(id):n.add(id);return n})}
 const outbound=useMemo(()=>{const m=new Map<string,string[]>();rows.filter(r=>selected.has(r.id)).forEach(r=>r.phones.forEach(p=>{const b=m.get(p)||[];if(!b.includes(r.buildingName))b.push(r.buildingName);m.set(p,b)}));return Array.from(m.entries()).map(([phone,buildings])=>({phone,buildings,message:messageTemplate.replaceAll("{건물명}",buildings.join(", "))}))},[rows,selected,messageTemplate]);
 function openMessage(phone:string,message:string){window.location.href=`sms:${phone}?body=${encodeURIComponent(message)}`}
 function clearLedger(){if(!confirm("이 브라우저에 저장된 문자 장부를 삭제할까요?"))return;localStorage.removeItem(LOCAL_KEY);setRows([]);setSelected(new Set());setStatus("브라우저에 저장된 장부를 삭제했습니다.")}
 return <main className="min-h-screen bg-[#F8F9FB] px-4 py-8 text-[#0A2342]"><div className="mx-auto max-w-[1500px] rounded-[32px] bg-white p-6 shadow-sm md:p-8">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">임대인 공실 확인 문자</h1><p className="mt-2 text-sm text-[#0A2342]/60">장부에서 임대인을 선택한 뒤 휴대폰 기본 문자 앱으로 넘겨 무료 문자 요금제를 사용합니다. 연락처는 이 브라우저에만 저장됩니다.</p></div><div className="flex gap-2"><label className="cursor-pointer rounded-xl border border-[#0A2342] px-5 py-3 text-sm font-semibold">현풍 원룸 장부 불러오기<input type="file" accept=".xlsx,.xls" className="hidden" onChange={handleExcel}/></label><button onClick={clearLedger} disabled={!rows.length} className="rounded-xl border px-5 py-3 text-sm font-semibold disabled:opacity-40">장부 삭제</button></div></div>
  <div className="mt-4 rounded-2xl bg-amber-50 p-4 text-sm leading-6"><b>사용 방법</b> : 휴대폰에서 관리자 페이지 접속 → 장부 불러오기 → 임대인 선택 → 오른쪽의 <b>문자 앱 열기</b> → 휴대폰 문자 앱에서 최종 전송. 별도 문자 API 요금은 없습니다.</div>
  <div className="mt-6 grid gap-4 lg:grid-cols-[1fr_420px]"><section><div className="flex flex-wrap items-center gap-3 rounded-2xl border bg-[#F8F9FB] p-4"><select value={area} onChange={e=>setArea(e.target.value)} className="rounded-xl border bg-white px-4 py-3">{areas.map(v=><option key={v}>{v}</option>)}</select><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="건물명·주소·소유자·전화번호 검색" className="min-w-[260px] flex-1 rounded-xl border bg-white px-4 py-3"/><span className="text-sm">검색 <b>{filtered.length}</b>개 · 선택 <b>{selected.size}</b>개</span></div>{status&&<p className="mt-3 rounded-xl bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-800">{status}</p>}<div className="mt-4 overflow-x-auto rounded-2xl border"><table className="w-full min-w-[900px] text-sm"><thead className="bg-[#F8F9FB]"><tr><th className="px-3 py-4 text-left"><input type="checkbox" checked={allSelected} onChange={toggleAll}/></th>{["구역","건물명","주소","소유자","공실 메모","전화번호"].map(v=><th key={v} className="px-3 py-4 text-left">{v}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t align-top"><td className="px-3 py-3"><input type="checkbox" disabled={!r.phones.length} checked={selected.has(r.id)} onChange={()=>toggleOne(r.id)}/></td><td className="px-3 py-3">{r.area}</td><td className="px-3 py-3 font-semibold">{r.buildingName}</td><td className="px-3 py-3">{r.lot||"-"}</td><td className="whitespace-pre-line px-3 py-3">{r.owner||"-"}</td><td className="whitespace-pre-line px-3 py-3">{r.vacancy||"-"}</td><td className="px-3 py-3">{r.phones.length?r.phones.map(displayPhone).join(" / "):<span className="text-red-500">번호 없음</span>}</td></tr>)}</tbody></table></div></section>
  <aside className="h-fit rounded-2xl border p-5 lg:sticky lg:top-[88px]"><h2 className="text-xl font-bold">휴대폰 문자 발송</h2><p className="mt-2 text-xs leading-5 text-[#0A2342]/55">{"{건물명}"}은 자동 변경됩니다. 같은 전화번호의 여러 건물은 한 문구로 묶습니다.</p><textarea value={messageTemplate} onChange={e=>setMessageTemplate(e.target.value)} rows={6} className="mt-4 w-full rounded-xl border p-3 leading-6"/><div className="mt-4 rounded-xl bg-[#F8F9FB] p-4 text-sm">문자 대상 <b>{outbound.length}명</b>{outbound.map((o,i)=><div key={o.phone} className="mt-3 border-t pt-3"><div className="flex items-center justify-between gap-2"><b>{displayPhone(o.phone)} · {o.buildings.join(", ")}</b><button type="button" onClick={()=>openMessage(o.phone,o.message)} className="shrink-0 rounded-lg bg-[#0A2342] px-3 py-2 text-xs font-bold text-white">문자 앱 열기</button></div><p className="mt-2 text-xs leading-5 text-[#0A2342]/65">{o.message}</p>{i===0&&<p className="mt-1 text-[11px] text-amber-700">휴대폰에서 버튼을 누르면 수신번호와 문구가 자동 입력됩니다. 전송 버튼만 눌러 주세요.</p>}</div>)}</div>{!outbound.length&&<p className="mt-4 rounded-xl bg-gray-50 p-4 text-sm text-gray-500">왼쪽에서 문자 보낼 건물을 선택하세요.</p>}<p className="mt-4 text-xs leading-5 text-[#0A2342]/55">브라우저 보안상 홈페이지가 전송 버튼을 대신 누르지는 않습니다. 실제 전송은 휴대폰 기본 문자 앱에서 확인 후 진행됩니다.</p></aside></div>
 </div></main>
}
